name: Sanity Check

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout private environment
      uses: actions/checkout@v2
      with: 
        repository: wbh123456/RingBell_environment
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        path: env
    - name: Combine two repos
      run: |
        mv env/environment.py environment.py

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install datetime
        pip install selenium
        pip install xlrd
        pip install xlutils
        pip install pymongo==3.12.1
    - name: Run matching algorithm test
      run: |
        python main.py --matching_algorithm_testing_mode
    - name: Run full program atomically
      run: |
        python main.py --run_atomically
